version: '3.8'
services:
  db:
    container_name: ecotiya_db_prod
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST:-%}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecotiya_com}
      MYSQL_USER: ${MYSQL_USER:-ecotiya}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ecotiya}
      TZ: ${TZ:-Asia/Tokyo}
    ports:
      - 3310:3306
    volumes:
      - ./mysql/data:/var/lib/mysql # 実データの永続化
      - ./mysql/log:/var/log/mysql  # logの永続化

  frontend:
    container_name: ecotiya_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    tty: true
    restart: always
    ports:
      - 80:80
    depends_on:
      backend:
          condition: service_started

  backend:
    container_name: ecotiya_backend_prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST:-%}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecotiya_com}
      MYSQL_USER: ${MYSQL_USER:-ecotiya}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ecotiya}
      TZ: ${TZ:-Asia/Tokyo}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://db/ecotiya_com}
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started