# Web
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  
  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/ecotiya_com
    username: ecotiya
    password: 8q_7PfepDM!Ect_7nvhh
    driverClassName: com.mysql.cj.jdbc.Driver