version: '3.8'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: ecotiya_mysql
    env_file:
      - ./mysql/db.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/settings/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql # 実データの永続化
      - ./mysql/log:/var/log/mysql  # logの永続化

  dbclient:
    image: phpmyadmin/phpmyadmin
    container_name: ecotiya_dbclient
    environment:
      - PMA_ARBITRARY=1         # 任意のサーバーへの接続を許可
      - PMA_HOST=ecotiya_mysql  # 接続先ホスト名　ここではdbサーバーのコンテナ名を指定
      - PMA_USER=root           # MySQLの設定と合わせておく
      - PMA_PASSWORD=root       # MySQLの設定と合わせておく
    links:
      - mysql
    ports:
      - 4200:100
    volumes:
      - ./dbclient/sessions:/sessions
    depends_on:
      - mysql # 「mysql」の後で起動

  # nginx:
  #   container_name: wicum_nginx_container
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   volumes:
  #     - public-data:/myapp/public
  #     - tmp-data:/myapp/tmp
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  frontend:
    container_name: ecotiya_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c 'yarn start'
    volumes:
      - ../../frontend:/app-frontend
    ports:
      - "8080:3000"
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecotiya_backend
    env_file:
      - ./mysql/db.env # mysqlと同じものを指定
    tty: true
    working_dir: /app-backend
    volumes:
      - ../backend:/app-backend # Spring Bootのプロジェクト
    ports:
      - 8080:8080 # 通常実行
      - 5050:5050 # デバッグ用
    depends_on:
      - mysql # 「mysql」の後で起動