version: '3.8'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: ecotiya_mysql
    env_file:
      - ./mysql/db.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/settings/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql # 実データの永続化
      - ./mysql/log:/var/log/mysql  # logの永続化

  # nginx:
  #   container_name: ecotiya_web
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   volumes:
  #     - public-data:/myapp/public
  #     - tmp-data:/myapp/tmp
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  frontend:
    container_name: ecotiya_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app-frontend
    volumes:
      - ../frontend:/app-frontend
    ports:
      - "3000:8080"
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecotiya_backend
    env_file:
      - ./mysql/db.env # mysqlと同じものを指定
    tty: true
    working_dir: /app-backend
    volumes:
      - ../backend:/app-backend # Spring Bootのプロジェクト
    ports:
      - 8080:8080 # 通常実行
    depends_on:
      - mysql # 「mysql」の後で起動