# Web
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  
  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3310/ecotiya_com
    username: ecotiya
    password: ecotiya
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true