# Web
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  
  # Datasource
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/ecotiya_com}
    username: ${MYSQL_USER:ecotiya}
    password: ${MYSQL_PASSWORD:ecotiya}
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true